@startuml exampletablediagram
skinparam 300 dpi
+class Suite {
	+ScenarioResult retryScenario(Scenario scenario)
	+Results updateResults(ScenarioResult sr)
}
+class FeatureParser {
	+enterScenarioOutline(KarateParser.ScenarioOutlineContext ctx)
}
+class ScenarioOutline {
	-List<ExamplesTable> examplesTables

	+List<Scenario> getScenarios(FeatureRuntime fr)
}
+class Scenario {
	-int exampleIndex
	-List<Tag> tags
	-Map<String, Object> exampleData;
	+boolean isEqualTo(Scenario other)
}
+class ExamplesTable {
	-ScenarioOutline outline
	-List<Tag> tags
}
+class ScenarioResult {
	-Scenaro scenario
	+ScenarioResult fromKarateJson(File workingDir, Feature feature, Map<String, Object> map)
	+Map<String, Object> toKarateJson()
	+int compareTo(ScenarioResult sr)
}

Suite --> ScenarioResult : "uses"
Suite --> Scenario : "uses"
FeatureParser --> ScenarioOutline : "creates"
FeatureParser --> ExamplesTable : "creates"
ScenarioOutline --> Scenario : "creates"
ScenarioOutline o-- ExamplesTable : "has multiple"
ScenarioResult o-- Scenario : "has a"
@enduml